- name: add nginx ppa
  apt_repository: repo='ppa:nginx/stable'

- name: install nginx-full
  apt: name=nginx-full state=present update_cache=yes

- name: run nginx with vagrant user
  lineinfile: dest=/etc/nginx/nginx.conf regexp='^user' line='user vagrant;'
  notify: restart nginx

- name: disable nginx sendifle
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'sendfile on;'
    line: 'sendfile off;'
    backrefs: yes
  notify: restart nginx

- name: render nginx site
  template: src=server.j2 dest=/etc/nginx/sites-available/{{ domain }}.conf
  notify: restart nginx

- name: enable nginx site
  file:
    src: /etc/nginx/sites-available/{{ domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain }}.conf
    state: link
  notify: restart nginx

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
