- name: add php ppa
  apt_repository: repo='ppa:ondrej/php' state=present

- name: update apt cache
  apt: update_cache=yes

- name: install php
  apt: name=php{{ php.version }} state=present
  notify:
    - restart apache2

- name: install php modules
  apt: name=php{{ php.version }}-{{ item }} state=present
  with_items: "{{ php.modules }}"
  notify:
    - restart apache2

- name: enable php modules
  command: phpenmod {{ item }}
  with_items: "{{ php.modules }}"
  notify:
    - restart apache2

- name: enable settings
  lineinfile:
    path: /etc/php/{{ php.version }}/apache2/php.ini
    regexp: "^{{ item.option }}"
    line: "{{ item.option }} = {{ item.value }}"
  with_items: "{{ php.settings }}"
  notify:
      - restart apache2
