- name: add php ppa
  apt_repository: repo='ppa:ondrej/php' state=present

- name: update apt cache
  apt: update_cache=yes

#- name: install php
#  apt: name=php{{ php.version }} state=present

- name: install php modules
  apt: name=php{{ php.version }}-{{ item }} state=present
  with_items: "{{ php.modules }}"

- name: enable php modules
  command: phpenmod {{ item }}
  with_items: "{{ php.modules }}"
